### ISSUE TITLE
Homebrew formula moved

### ISSUE THREAD

**Issue by ahtotruu** [tamarin-prover/manual-pandoc#40]
The Homebrew/Linuxbrew formula for Tamarin has moved from `homebrew/science/tamarin-prover` to `brewsci/science/tamarin-prover`.

**Comment by rsasse** [comment]
Thanks for the heads-up! Fixed as of commit 900a0e5e131acf2230a1db51d0a146077a3439ad right now.

**Comment by ahtotruu** [comment]
Coming back to this a bit late, but it seems to me you missed a couple of spots. Please see the enclosed patch file. (Had to ZIP it for GH to accept the attachement.)
[002_installation.zip](https://github.com/tamarin-prover/manual/files/1833416/002_installation.zip)

**Comment by rsasse** [comment]
Thanks for your patch, but it is relevant for an outdated version only by now. I went through it carefully, but there is no reference to brewsci anymore in our current manual. This is possible thanks to us hosting our own tap for tamarin-prover now at https://github.com/tamarin-prover/homebrew-tap due to @katrielalex , for documentation see  https://github.com/tamarin-prover/manual/commit/a558293346de0b8a272a795be82a114c1675f157

**Comment by ahtotruu** [comment]
Ah, so much the better. Probably going to be more stable in the long run :)
